name: laravel-filament-skeleton-project

services:
  laravel-filament-skeleton_app:
    image: serversideup/php:8.4-fpm-nginx
    container_name: laravel-filament-skeleton_webserver
    ports:
      - '8888:80'
      - '444:443'
    volumes:
      - .:/var/www/html/:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - AUTORUN_ENABLED=false
      - SSL_MODE=mixed
    networks:
      - laravel-filament-skeleton_network
  
  laravel-filament-skeleton_task:
    build:
      context: .
      dockerfile: Dockerfile-cli
    container_name: laravel-filament-skeleton_task
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_FPM_POOL_NAME: "laravel-filament-skeleton_task"
    networks:
      - laravel-filament-skeleton_network
  
  laravel-filament-skeleton_queue:
    build:
      context: .
      dockerfile: Dockerfile-cli
    container_name: laravel-filament-skeleton_queue
    command: ["php", "/var/www/html/artisan", "queue:work"]
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_FPM_POOL_NAME: "laravel-filament-skeleton_queue"
    networks:
      - laravel-filament-skeleton_network
  
  laravel-filament-skeleton_redis:
    container_name: laravel-filament-skeleton_redis
    image: redis:7.0-alpine
    command: "redis-server --appendonly yes --requirepass redispassword"
    networks:
      - laravel-filament-skeleton_network
  
  laravel-filament-skeleton_db:
    container_name: laravel-filament-skeleton_db
    image: mysql:8.3
    ports:
      - '3305:3306'
    volumes:
      - laravel-filament-skeleton-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    networks:
      - laravel-filament-skeleton_network

volumes:
  laravel-filament-skeleton-db:
    driver: local

networks:
  laravel-filament-skeleton_network:
